version: "3.9"

services:
  db:
    image: postgres:16
    container_name: banco_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: banco_user
      POSTGRES_PASSWORD: banco_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: ./fastapi_app
    container_name: banco_fastapi
    restart: unless-stopped
    environment:
      DB_USER: banco_user
      DB_PASSWORD: banco_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: banco_db
    depends_on:
      - db
    ports:
      - "8000:8000"

  flask:
    build: ./flask_app
    container_name: banco_flask
    restart: unless-stopped
    environment:
      FASTAPI_BASE_URL: http://fastapi:8000
    depends_on:
      - fastapi
    ports:
      - "5000:5000"

volumes:
  pgdata: